apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.deploymentName }}-vss
  namespace: {{ .Values.namespace }}
spec:
  vaultAuthRef: {{ .Values.vaultAuthRef }}
  type: kv-v2
  mount: {{ .Values.vaultMount }}
  path: {{ .Values.vaultPath }}
  destination:
    name: {{ .Values.secretName }}
    create: true
  refreshAfter: {{ .Values.vaultRefreshAfter }}
